name: Unit Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      # A workaround to trigger the workflow for pull requests from forked repository,
      # which does not have access to secrets.
      #
      # This is also useful for testing the workflow without opening a pull request.
      - tmp/*
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 */4 * * 1-5

# Default permissions for all jobs
permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/master' }}"

jobs:
  junit:
    name: dd/junit
    if: ${{ !cancelled() }}
    runs-on: ubuntu-24.04
    container:
      image: datadog/ci
      credentials:
        username: "${{ secrets.NOT || '' }}"
        password: "${{ secrets.NOT || '' }}"
      env:
        DD_API_KEY: "${{ secrets.DD_API_KEY }}"
        DD_ENV: ci
        DATADOG_SITE: datadoghq.com
        DD_SERVICE: dd-trace-rb
        DD_GIT_REPOSITORY_URL: "${{ github.repositoryUrl }}"
    steps:
      - run: echo "DONE!"
